### PR TITLE
upgrade node version

### PR DESCRIPTION
**Pull request by ISO50**
- LTS 8.11.4
- Current 10.9.0
- added RoP relevant files

### CODE REVIEW

**Comment by ISO50** [comment]
@kgalli could you add me to the repo managment group?

**Comment by mikkeloscar** [comment]
:+1:

**Comment by mikkeloscar** [comment]
For reference: https://nodejs.org/en/blog/vulnerability/august-2018-security-releases/

**Comment by zeddmalam** [comment]
👍

**Comment by roflc0pter** [comment]
:+1:

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
