### PR TITLE
Upgrade version: npm@5

### LINKED ISSUE #33: npm@5
npm@5 was released with lots of nice features and better performance.

http://blog.npmjs.org/post/161276872334/npm5-is-now-npmlatest

Does it make sense to update it in `stable`?

### PR DESCRIPTION
**Pull request by shuhei**
Upgrading npm of `stable`. Leaving `lts` as is because [Node.js LTS doc](https://github.com/nodejs/LTS#lts-plan) says LTS is limited to "Non-semver-major npm updates".

Also, changing `npm cache clear` (alias of `npm cache clean`) to `npm cache clean --force` because now the command requires `--force`. https://docs.npmjs.com/cli/cache#details

Fixes #33

### CODE REVIEW

**Comment by harti2006** [comment]
:+1:

**Comment by hjacobs** [comment]
Let's do #35 before we merge anything and release a new image :smile:

**Comment by harti2006** [comment]
@shuhei what about updating nodejs to the latest stable version (8.1.2) as well?

**Comment by shuhei** [comment]
@harti2006 If you are OK with it, I'm OK too. I just wanted to use npm 5's package-lock.json.

**Comment by kgalli** [comment]
@shuhei please update to the most recent version of NPM (currently `5.1.0`) and I can merge the change.

@harti2006 from my point of view we can switch to `8.1.3` because it is the stable node version now. Please create a PR and it can be merged as well.

**Comment by harti2006** [comment]
:+1:

**Comment by kgalli** [comment]
👍

**Comment by kgalli** [comment]
@harti2006 What do you think about using yarn and follow the official docker node repo?

**Comment by harti2006** [comment]
@kgalli I don't have experience with yarn. we are using our own docker base images, based on ubuntu, because they include the Zalando cert authority.
Teams are not require to use it, but could instead use official docker node images as a base for their docker images.

**Comment by shuhei** [comment]
@harti2006 Thanks for updating the version :-)

**Pull request merged**
