### PR TITLE
#46 add alpine builds

### PR DESCRIPTION
**Pull request by lufzle**
Provides alpine alternative for both LTS and Current.

### CODE REVIEW

**Comment by kgalli** [comment]
@luisfarzati is there a particular reason why you added `yarn` here or is it just because it is the snippet used by the official node image. I kind of do not like to have `npm` used in some images  and `yarn` in others.

We could also just follow the official node image to minimise the effort on our end. But I think we should agree on an approach.

**Comment by lufzle** [comment]
Agree on having npm for consistency. I just copied the original Dockerfile. I'll remove yarn.

**Comment by kgalli** [comment]
👍

**Comment by lufzle** [comment]
Removed yarn.-

**Comment by kgalli** [comment]
👍

**Comment by lufzle** [comment]
👍

**Pull request merged**
