### PR TITLE
Update releases to recent versions

### PR DESCRIPTION
**Pull request by kgalli**
Update recent versions:
- lts: 4.4.5
- stable: 6.2.1

### CODE REVIEW

**Comment by prayerslayer** [comment]
`npm` is already at `3.9.6` 😁

**Comment by kgalli** [comment]
Are you sure this is the current stable version? It is a prerelease for me https://github.com/npm/npm/releases. Do you still think we should update?

**Comment by prayerslayer** [comment]
Oh, i only checked with `npm info npm`. In this case 3.9.5 is of course fine.

**Comment by prayerslayer** [comment]
Releases:
- `registry.opensource.zalan.do/stups/node:4.4-29`
- `registry.opensource.zalan.do/stups/node:6.2-31`

**Pull request merged**
