### PR TITLE
Dockerfile: update to 7.10.1

### PR DESCRIPTION
**Pull request by artdaw**
Closes https://github.com/zalando-stups/docker-node/issues/37

### CODE REVIEW

**Comment by kgalli** [comment]
@artdaw thanks for the PR. Will do a quick check and merge if it is fine.

**Comment by kgalli** [comment]
👍

**Comment by kgalli** [comment]
@artdaw can you thumb up so I can merge this one?

**Comment by artdaw** [comment]
👍

**Pull request merged**
