### PR TITLE
Update to latest releases

### PR DESCRIPTION
**Pull request by kgalli**
- [x] Update LTS to `10.15.1`
- [x] Update CURRENT to `11.8.0`

### CODE REVIEW

**Comment by kgalli** [comment]
👍

**Comment by kgalli** [comment]
@ISO50 @cberg-zalando can you please have a look?

**Comment by cberg-zalando** [comment]
I guess, its totally fine to not provide "oldlts" versions and instead update to what the nodejs community is now marketing as current and lts. :smile:

**Comment by cberg-zalando** [comment]
:+1:

**Pull request merged**
