### PR TITLE
Bump versions to recent ones

### PR DESCRIPTION
**Pull request by kgalli**
This PR bump all versions (ancient, stable and lts) to the most recent ones. Due to the fact that version 6 is not LTS and version 4 as well I did not change anything in regard to stable and lts.

### CODE REVIEW

**Comment by kgalli** [comment]
@prayerslayer right now I'm not able to build those dockerfiles by myself due to the fact that `ha.pool.sks-keyservers.net` seems to be down or something. But maybe it is just my machine. So this info is just if you see the same issue.

**Comment by prayerslayer** [comment]
Shouldn't v6 be LTS by now? https://github.com/nodejs/LTS#lts-schedule

> ha.pool.sks-keyservers.net

Related to [this](https://www.dynstatus.com/incidents/nlr4yrr162t8) maybe? I don't know.

**Comment by kgalli** [comment]
You are right v6 is LTS now. But when you look at https://nodejs.org/en/ you can see v4 and v6 are considered LTS for the moment. So my suggestion is we keep our structure for now because there is no v7 stable or something.

**Comment by kgalli** [comment]
Building node works now by the way. So you might be the DOS attack you linked.

**Comment by kgalli** [comment]
@prayerslayer are you going to merge this PR or do you want me to change something?

**Comment by prayerslayer** [comment]
Will merge.

**Pull request merged**
