### PR TITLE
Bump versions

### PR DESCRIPTION
**Pull request by prayerslayer**

### CODE REVIEW

**Comment by prayerslayer** [comment]
Pinging @kgalli :smiley:

**Comment by kgalli** [comment]
@prayerslayer looks good to me. Can you give me permissions to actually merge this? Otherwise I can just confirm and you merge it by yourself ;-) ... As a side note: Do we want to have one commit per version change? Like one for LTS and so on. Or like what you did in the past like bump all versions. Just curious because I did one for each version (LTS, Stable). I think it makes sense we agree on one scheme. No preference from my side though.

**Comment by prayerslayer** [comment]
I'd prefer one for all updates as this reduces the amount of builds in our Go pipeline, but really I don't care :)

**Comment by prayerslayer** [comment]
Also you should be a collaborator now. Can you merge?

**Comment by kgalli** [comment]
Perfect I can merge. Will do some testing first though.

**Comment by prayerslayer** [comment]
Releases:
- `registry.opensource.zalan.do/stups/node:0.12-16`
- `registry.opensource.zalan.do/stups/node:4.3-16`
- `registry.opensource.zalan.do/stups/node:5.7-17`

**Comment by kgalli** [comment]
:+1:

**Pull request merged**
