### PR TITLE
Update alpine and configuration to the latest

### PR DESCRIPTION
**Pull request by mikkeloscar**
* Use alpine latest as base image.
* Update `delivery.yaml` to new format.

Since the build was failing this also updates the Dockerfile configurations to be based on the latest version from https://github.com/nodejs/docker-node

### CODE REVIEW

**Comment by hjacobs** [comment]
Are the maintainers (Karsten Gallinowski <karsten.gallinowski@zalando.de> @kgalli, Jörg Dotzki <joerg.dotzki@zalando.de> according to `MAINTAINERS` file) still active? I wonder whether we should take care of this (always good to fix/update, but we don't run node.js ourselves).

**Comment by kgalli** [comment]
@mikkeloscar LGTM. Thanks for the PR.

**Comment by kgalli** [comment]
👍

**Comment by kgalli** [comment]
> I wonder whether we should take care of this ...

@hjacobs who would be "we" in your question?

**Comment by hjacobs** [comment]
@kgalli sorry, "we" was Platform Infrastructure in this case. I just struggle to see clear maintainers for this base image as we (as Platform Infrastructure) don't use it AFAIK. Ubuntu, OpenJDK and Python are clear candidates to be maintained by us, node.js less so.

**Comment by mikkeloscar** [comment]
:+1:

**Comment by kgalli** [comment]
@mikkeloscar or @ISO50 can you please thumb it up so we can merge this PR.

**Comment by kgalli** [comment]
@mikkeloscar never mind. Obviously  I did not refresh the page.

**Comment by kgalli** [comment]
@hjacobs is there a particular reason why we base all our docker images from ubuntu? I have this idea in mind to automate the whole process of updating our docker images whenever the official image gets updated. This could be easily done by just applying our changes on top of the official image and push to docker registry. Of course that means our "base" image would have the official image as base image which is most likely not Ubuntu. But would that be a problem?

Maybe you can add your thoughts?

**Comment by hjacobs** [comment]
@kgalli I don't have any strong opinion on the node.js image, if you want to support & improve it: use the base image which fits best for you.

**Pull request merged**
