### PR TITLE
#53 upgrade node to 8.8.0

### LINKED ISSUE #53: Node 8.8.0 with critical DOS security vulnerability fix
Was released yesterday, you might want to make it available as all previous 8.x.x versions are affected.

https://nodejs.org/en/blog/vulnerability/oct-2017-dos/

### PR DESCRIPTION
**Pull request by mrac**
Closes #53

### CODE REVIEW

**Comment by kgalli** [comment]
👍

**Comment by kgalli** [comment]
@luisfarzati can you have a look please and merge if it is fine?

**Comment by kgalli** [comment]
@mrac can you please update to 8.9.0.

**Comment by kgalli** [comment]
@luisfarzati what do you think about updating LTS and Current to 8.9.0 and 9.0.0.

**Comment by mrac** [comment]
@kgalli may be I could create another branch/PR because this one is explicitly named `8.8.0`. 
BTW it looks like 8.9.0 is nothing more but some docs added and tests

**Comment by lufzle** [comment]
👍

**Comment by lufzle** [comment]
Sorry for the late response. :) If @mrac can submit another PR with latest LTS & Current release lines would be great. Otherwise I can do it maybe next week.

**Pull request merged**
