### PR TITLE
Update lts and current to latest

### PR DESCRIPTION
**Pull request by kgalli**
This PR updates lts and current to the latest:

* lts `8.12.0`
* currten `10.12.0`

### CODE REVIEW

**Comment by kgalli** [comment]
@ISO50 please have a look.

**Comment by kgalli** [comment]
ping @ISO50

**Comment by cberg-zalando** [comment]
If we wait one additional day, 8.12.0 will be the old LTS as LTS for 10.x will start by the [30th of October](https://github.com/nodejs/Release#release-schedule).

**Comment by kgalli** [comment]
@cberg-zalando I do not want to hold back this one even though it will be outdated soon. I will make an additional PR when necessary.

So please consider to thumb up this one so I can merge this one.

**Comment by cberg-zalando** [comment]
:+1:

**Comment by kgalli** [comment]
👍

**Comment by kgalli** [comment]
👍

**Comment by kgalli** [comment]
@cberg-zalando Any idea why zappr does not recognise my thumb up? Would really like to get this one merged. Next I will update lts / current to 10.13.0 LTS and 11.1.0 Current.

**Comment by cberg-zalando** [comment]
Its actually not your thumb up being taken into account, but mine. You're listed as a project contributor whereas I am not. So I guess, zappr only takes contributors into account. But as I'm in the same office as @ISO50, I can just personally nag to get this merged so that we can continue here.

**Comment by szuecs** [comment]
We have feature freeze, does it makes sense to merge it now?

**Comment by kgalli** [comment]
@szuecs it does. Whoever has a feature freeze will anyhow not pull this change. And for those who do not have feature freeze we can move on. So please let's get this one merged.

**Comment by kgalli** [comment]
Ping @ISO50 ...

**Comment by ISO50** [comment]
Sorry I didn't receive email notifications.
+1

**Comment by ISO50** [comment]
👍

**Comment by ISO50** [comment]
Spam folder 🤦‍♂️

**Pull request merged**
