### PR TITLE
End special treatment for AppDynamics

### PR DESCRIPTION
**Pull request by kgalli**
As of AppDynamics Agent 4.2.4 there is no need to have
a special node version which supports AppDynamics.

See the following post:

https://docs.appdynamics.com/display/PRO42/Node.js+Supported+Environments

As of 4.2.4, the Node.js Agent supports all major and minor versions of
Node.js v0, v4, v5, and v6. Further, the agent no longer needs to be
updated for each new minor version update of Node.js.

### CODE REVIEW

**Comment by prayerslayer** [comment]
Should we also end support for `ancient`? I don't see why people would use it.

**Comment by kgalli** [comment]
I say we follow the official [LTS schedule](https://github.com/nodejs/LTS#lts_schedule) and also end ancient with the beginning of next year.

I also checked and we can merge this PR right away because AppDynamics agent version >= `4.2.4` is now supported by our setup.

**Comment by kgalli** [comment]
@prayerslayer let's merge this one and if we agree on removing ancient as well I will create a new PR. What do you think?

**Comment by prayerslayer** [comment]
As far as I understood in order to drop our AD line we need a certain AD controller version available. Let me check back if that's the case already.

**Comment by kgalli** [comment]
Team collab is using the new setup already. It is working fine.

**Comment by prayerslayer** [comment]
> Team collab is using the new setup already. It is working fine.

In this case I have no objections.

**Comment by prayerslayer** [comment]
Question: Current stable is 7.2.0 and appdynamics supports 6.x - should we still end special appdynamics treatment? I'm fine with relying on appdynamics supporting latest LTS.

**Comment by kgalli** [comment]
@prayerslayer I rebased this so it can easily be merged. LTS supporting appdynamics should be enough.

**Comment by prayerslayer** [comment]
Cool, thanks!

**Pull request merged**
