### PR TITLE
Fix missing gnupg to be able to verify node

### PR DESCRIPTION
**Pull request by kgalli**
I took the snippet from: https://github.com/docker-library/buildpack-deps/blob/b0fc01aa5e3aed6820d8fed6f3301e0542fbeb36/stretch/curl/Dockerfile.

### CODE REVIEW

**Comment by kgalli** [comment]
@ISO50 I created the PR please have a look.

**Comment by kgalli** [comment]
@ISO50 maybe it is possible to move this install step to https://github.com/zalando-stups/docker-ubuntu but for now it is necessary here.

**Comment by ISO50** [comment]
👍

**Comment by kgalli** [comment]
👍

**Pull request merged**
